export const feedBacks = [
    {
        id: 1,
        firstName: 'Tran',
        lastName: 'Thanh Cong',
        email: 'congttse@gmail.com',
        phone: '0123456789',
        place: 'Viet Nam',
        subject: 'FER201m',
        message: 'Tran Thanh Cong congttse@gmail.com 0123456789',
        switch: true,
    },
    {
        id: 2,
        firstName: 'Nguyen',
        lastName: 'Tam Thien',
        email: 'thienntse@gmail.com',
        phone: '0123456788',
        place: 'USA',
        subject: 'SWP301',
        message: 'Nguyen Tam Thien thienntse@gmai.com 0123456788',
        switch: true,
    },
    {
        id: 3,
        firstName: 'Tran',
        lastName: 'Minh Huy',
        email: 'huytmse@gmail.com',
        phone: '0123456787',
        place: 'England',
        subject: 'SWT201',
        message: 'Tran Minh Huy huytmse@gmail.com 0123456787',
        switch: true,
    },
    {
        id: 4,
        firstName: 'Ton',
        lastName: 'Nu Bao Tran',
        email: 'trantnbss@gmail.com',
        phone: '0123456786',
        place: 'Viet Nam',
        subject: 'MKT113',
        message: 'Ton Nu Bao Tran trantnbss@gmail.com 0123456786',
        switch: true,
    },
    {
        id: 5,
        firstName: 'Nguyen',
        lastName: 'Van Mau',
        email: 'maunvss@gmail.com',
        phone: '0123456785',
        place: 'USA',
        subject: 'SWR301',
        message: 'Nguyen Van Mau maunvss@gmail.com 0123456785',
        switch: true,
    },
    {
        id: 6,
        firstName: 'Ton',
        lastName: 'Trong Nghia',
        email: 'nghiattse@gmail.com',
        phone: '0123456784',
        place: 'Australia',
        subject: 'SWP201',
        message: 'Ton Trong Nghia nghiattse@gmail.com 0123456784',
        switch: true,
    },
    {
        id: 7,
        firstName: 'Than',
        lastName: 'Nhat Truong',
        email: 'truongtnse@gmail.com',
        phone: '0123456783',
        place: 'France',
        subject: 'LAB211',
        message: 'Than Nhat Truong truongtnse@gmail.com 0123456783',
        switch: true,
    },
    {
        id: 8,
        firstName: 'Tran',
        lastName: 'Anh Tuan',
        email: 'tuantass@gmail.com',
        phone: '0123456782',
        place: 'Canada',
        subject: 'PRJ301',
        message: 'Tran Anh Tuan tuantass@gmail.com 0123456782',
        switch: true,
    },
    {
        id: 9,
        firstName: 'Huynh',
        lastName: 'Minh Bao',
        email: 'baohmse@gmail.com',
        phone: '0123456781',
        place: 'France',
        subject: 'PRO201',
        message: 'Huynh Minh Bao baohmse@gmail.com 0123456781',
        switch: true,
    }
];